package bus_reservation_system;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author priya
 */
import java.awt.Color;
import java.sql.*;
//import javax.swing.*;
public class Book_seat extends javax.swing.JFrame {

    /**
     * Creates new form Book_seat
     */
        Connection conn=Connect.ConnectDB();
        ResultSet rs = null;
PreparedStatement pst = null;

int s1=2;
int s2=2;
int s3=2;
int s4=2;
int s5=2;
int s6=2;
int s7=2;
int s8=2;
int s9 =2;
int s10=2;
int s11=2;
int s12=2;
int s13=2;
int s14=2;
int s15=2;
int s16=2;
int s17=2;
int s18=2;
int s19=2;
int s20=2;
int s21=2;
int s22=2;
int s23=2;
int s24=2;
int s25=2;
int s26=2;
int s27=2;
int s28=2;
int s29=2;
int s30=2;
int s31=2;
int s32=2;
int a1=0;
int a2=0;
int a3=0;
int a4=0;
int a5=0;
int a6 = 0;
int a7=0;
int a8=0;
int a9=0;
int a10=0;
int a11=0;
int a12=0;
int a13=0;
int a14=0;
int a15=0;
int a16=0;
int a17=0;
int a18=0;
int a19=0;
int a20=0;
int a21=0;
int a22=0;
int a23=0;
int a24=0;
int a25=0;
int a26=0;
int a27=0;
int a28=0;
int a29=0;
int a30=0;
int a31=0;
int a32=0;

    public Book_seat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        seat1 = new javax.swing.JButton();
        seat2 = new javax.swing.JButton();
        seat3 = new javax.swing.JButton();
        seat4 = new javax.swing.JButton();
        seat5 = new javax.swing.JButton();
        seat6 = new javax.swing.JButton();
        seat8 = new javax.swing.JButton();
        seat9 = new javax.swing.JButton();
        seat10 = new javax.swing.JButton();
        seat11 = new javax.swing.JButton();
        seat12 = new javax.swing.JButton();
        seat13 = new javax.swing.JButton();
        seat15 = new javax.swing.JButton();
        seat14 = new javax.swing.JButton();
        seat16 = new javax.swing.JButton();
        seat7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        seat19 = new javax.swing.JButton();
        seat18 = new javax.swing.JButton();
        seat20 = new javax.swing.JButton();
        seat21 = new javax.swing.JButton();
        seat23 = new javax.swing.JButton();
        seat22 = new javax.swing.JButton();
        seat24 = new javax.swing.JButton();
        seat26 = new javax.swing.JButton();
        seat25 = new javax.swing.JButton();
        seat27 = new javax.swing.JButton();
        seat28 = new javax.swing.JButton();
        seat29 = new javax.swing.JButton();
        seat30 = new javax.swing.JButton();
        seat31 = new javax.swing.JButton();
        seat32 = new javax.swing.JButton();
        seat17 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("                CHOOSE YOUR SEAT");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));

        seat1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat1.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat1.setText("1");
        seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat1ActionPerformed(evt);
            }
        });

        seat2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat2.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat2.setText("2");

        seat3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat3.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat3.setText("3");
        seat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat3ActionPerformed(evt);
            }
        });

        seat4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat4.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat4.setText("4");
        seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat4ActionPerformed(evt);
            }
        });

        seat5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat5.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat5.setText("5");
        seat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat5ActionPerformed(evt);
            }
        });

        seat6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat6.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat6.setText("6");
        seat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat6ActionPerformed(evt);
            }
        });

        seat8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat8.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat8.setText("8");
        seat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat8ActionPerformed(evt);
            }
        });

        seat9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat9.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat9.setText("9");
        seat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat9ActionPerformed(evt);
            }
        });

        seat10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat10.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat10.setText("10");
        seat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat10ActionPerformed(evt);
            }
        });

        seat11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat11.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat11.setText("11");
        seat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat11ActionPerformed(evt);
            }
        });

        seat12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat12.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat12.setText("12");
        seat12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat12ActionPerformed(evt);
            }
        });

        seat13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat13.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat13.setText("13");
        seat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat13ActionPerformed(evt);
            }
        });

        seat15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat15.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat15.setText("15");
        seat15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat15ActionPerformed(evt);
            }
        });

        seat14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat14.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat14.setText("14");
        seat14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat14ActionPerformed(evt);
            }
        });

        seat16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat16.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat16.setText("16");
        seat16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat16ActionPerformed(evt);
            }
        });

        seat7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat7.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat7.setText("7");
        seat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(seat13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seat14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(seat11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seat12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(seat9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seat10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(seat7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seat8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(seat5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(seat6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(seat15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seat16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat1)
                    .addComponent(seat2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat3)
                    .addComponent(seat4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat5)
                    .addComponent(seat6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat8)
                    .addComponent(seat7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(seat9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seat11)
                            .addComponent(seat12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seat13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seat14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seat16)
                            .addComponent(seat15)))
                    .addComponent(seat10)))
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 153));

        seat19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat19.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat19.setText("19");
        seat19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat19ActionPerformed(evt);
            }
        });

        seat18.setBackground(new java.awt.Color(255, 255, 255));
        seat18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat18.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat18.setText("18");
        seat18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat18ActionPerformed(evt);
            }
        });

        seat20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat20.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat20.setText("20");
        seat20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat20ActionPerformed(evt);
            }
        });

        seat21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat21.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat21.setText("21");

        seat23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat23.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat23.setText("23");
        seat23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat23ActionPerformed(evt);
            }
        });

        seat22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat22.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat22.setText("22");
        seat22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat22ActionPerformed(evt);
            }
        });

        seat24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat24.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat24.setText("24");
        seat24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat24ActionPerformed(evt);
            }
        });

        seat26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat26.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat26.setText("26");
        seat26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat26ActionPerformed(evt);
            }
        });

        seat25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat25.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat25.setText("25");
        seat25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat25ActionPerformed(evt);
            }
        });

        seat27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat27.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat27.setText("27");
        seat27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat27ActionPerformed(evt);
            }
        });

        seat28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat28.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat28.setText("28");
        seat28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat28ActionPerformed(evt);
            }
        });

        seat29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat29.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat29.setText("29");
        seat29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat29ActionPerformed(evt);
            }
        });

        seat30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat30.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat30.setText("30");
        seat30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat30ActionPerformed(evt);
            }
        });

        seat31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat31.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat31.setText("31");

        seat32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat32.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat32.setText("32");

        seat17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat17.setIcon(new javax.swing.ImageIcon("C:\\Users\\priya\\OneDrive\\Desktop\\seat3.png")); // NOI18N
        seat17.setText("17");
        seat17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat22, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat24, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(seat25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seat26, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat27, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat29, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat31, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seat30, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat28, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat32, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(seat19, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seat20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(seat17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seat18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat18)
                    .addComponent(seat17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat19)
                    .addComponent(seat20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat21)
                    .addComponent(seat22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat23)
                    .addComponent(seat24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat25)
                    .addComponent(seat26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat27)
                    .addComponent(seat28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat30)
                    .addComponent(seat29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat32)
                    .addComponent(seat31)))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("< <");

        ok.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ok.setText("OK");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seat18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat18ActionPerformed
        // TODO add your handling code here:
        if (s18 >= 2 ) {seat18.setBackground(Color.GREEN);
a18=1;
s18=0;
}
else{
seat18.setBackground(Color.gray);
a18=0;
s18=2;
}
    }//GEN-LAST:event_seat18ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat4ActionPerformed
        if (s4 >=2){ seat4.setBackground(Color.GREEN);
a4=1;
s4=0;
}
else{
seat4.setBackground(Color.gray);
a4=0;
s4=2;
}   // TODO add your handling code here:
    }//GEN-LAST:event_seat4ActionPerformed

    private void seat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat5ActionPerformed
      if (s5>=2) {seat5.setBackground(Color.GREEN);
a5=1;
s5=0;     
}
else{
seat5.setBackground(Color.gray);
a5=0;
s5=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat5ActionPerformed

    private void seat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat6ActionPerformed
      if(s6 >= 2 ){ seat6. setBackground(Color.GREEN);
a6=1;
s6=0;
}
else{
seat6. setBackground(Color.gray);
a6=0;
s6=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat6ActionPerformed

    private void seat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat7ActionPerformed
     if (s7 >= 2){ seat7.setBackground(Color.GREEN);
a7=1;
s7=0;
}
else{
seat7.setBackground(Color.gray);
a7=0;
s7=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat7ActionPerformed

    private void seat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat8ActionPerformed
        if(s8>=2) { seat8.setBackground(Color.GREEN);
a8=1;
s8=0;
}
else{

seat8.setBackground(Color.gray);
a8=0;
s8=2;
}   // TODO add your handling code here:
    }//GEN-LAST:event_seat8ActionPerformed

    private void seat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat9ActionPerformed
        if (s9 >= 2){  seat9.setBackground(Color.GREEN);
a9=1;
s9= 0;
}
else{
seat9.setBackground(Color.gray);
a9=0;
s9=2;
}   // TODO add your handling code here:
    }//GEN-LAST:event_seat9ActionPerformed

    private void seat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat10ActionPerformed
       if (s10>=2) {seat10.setBackground(Color.GREEN);
a10=1;
s10=0;
}
else{
seat10.setBackground(Color.gray);
a10=0;
s10=2;}   // TODO add your handling code here:
    }//GEN-LAST:event_seat10ActionPerformed

    private void seat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat11ActionPerformed
       if (s11>=2) { seat11.setBackground(Color.GREEN);
a11=1;
s11=0;
}
else{
seat11.setBackground(Color.gray);
a11=0;
s11=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat11ActionPerformed

    private void seat12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat12ActionPerformed
      if (s12 >=2)
{ seat12.setBackground(Color. GREEN);
a12=1;
s12=0;
}
else{
seat12.setBackground(Color.gray);
a11=0;
s12=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat12ActionPerformed

    private void seat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat13ActionPerformed
       if(s13>= 2) {seat13.setBackground(Color.GREEN);
a13=1;
s13=0;
}
else{
seat13.setBackground(Color.gray);
a13=0;
s13=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat13ActionPerformed

    private void seat14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat14ActionPerformed
     if (s14>=2){ seat14.setBackground(Color.GREEN);
a14=1;
s14=0;
}
else {
seat14.setBackground(Color.gray);
a14=0;
s14=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat14ActionPerformed

    private void seat15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat15ActionPerformed
      if (s15>=2) {seat15.setBackground(Color.GREEN);
a15=1;
s15=0;
}
else {
seat15.setBackground(Color.gray);
a15=0;
s15=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat15ActionPerformed

    private void seat16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat16ActionPerformed
       if (s16 >= 2 ) { seat16.setBackground(Color.GREEN);
a16=1;
s16= 0;
}
else {
seat16.setBackground(Color.gray);
a16=0;
s16 =2;
}   // TODO add your handling code here:
    }//GEN-LAST:event_seat16ActionPerformed

    private void seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat1ActionPerformed
      if (s1 >=2 ){ seat1.setBackground(Color.GREEN);
a1=1;
s1= 0;
}
else {
seat1.setBackground(Color.gray);
a1=0;
s1=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat1ActionPerformed

    private void seat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat3ActionPerformed
       if (s3 >=2) { seat3.setBackground(Color.GREEN);
a3=1;
s3=0;
}
else{
seat3.setBackground(Color.gray);
a3=0;
s3=2;
}     // TODO add your handling code here:
    }//GEN-LAST:event_seat3ActionPerformed

    private void seat24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat24ActionPerformed
      if (s24 >= 2){ seat24.setBackground(Color.GREEN);
a24=1;
s24 = 0;
}
else{
seat24.setBackground(Color.gray);
a24=0;
s24=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat24ActionPerformed

    private void seat19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat19ActionPerformed
          if (s19 >=2) {seat19.setBackground(Color.GREEN);
a19=1;
s19=0;
}
else{
seat19.setBackground(Color.gray);
a19=0;
s19=2;
}   // TODO add your handling code here:
    }//GEN-LAST:event_seat19ActionPerformed

    private void seat20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat20ActionPerformed
      if (s20>=2){ seat20.setBackground(Color.GREEN);
a20=1;
s20=0;
}
else{
seat20.setBackground(Color.gray);
a20=0;
s20=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat20ActionPerformed

    private void seat22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat22ActionPerformed
       if (s22>=2 ) {seat22.setBackground(Color.GREEN);
a22=1;
s22=0;
}
else {
seat22.setBackground(Color.gray);
a22=0;
s22=2;
}  // TODO add your handling code here:
    }//GEN-LAST:event_seat22ActionPerformed

    private void seat25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat25ActionPerformed
     if (s25 >=2){ seat25.setBackground(Color.GREEN);
a25=1;
s25=0;
}
else{
seat25.setBackground(Color.gray);
a25=0;
s25=2;
     }// TODO add your handling code here:
    }//GEN-LAST:event_seat25ActionPerformed

    private void seat26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat26ActionPerformed
        if(s26 >=2) {  seat26.setBackground(Color.GREEN);
a26=1;
s26=0;
}
else{
seat26.setBackground(Color.gray);
a26=0;
s26=2;

}   // TODO add your handling code here:
    }//GEN-LAST:event_seat26ActionPerformed

    private void seat27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat27ActionPerformed
        if (s27>= 2){ seat27.setBackground(Color.GREEN);
a27=1;
s27=0;
}
else {
seat27.setBackground(Color.gray);
a27=0;
s27=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat27ActionPerformed

    private void seat28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat28ActionPerformed
     if (s28 >= 2) {seat28.setBackground(Color.GREEN);
a28=1;
s28=0;
     }
    else {
seat28.setBackground(Color.gray);
a28=0;
s28=2;
}      // TODO add your handling code here:
    }//GEN-LAST:event_seat28ActionPerformed

    private void seat30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat30ActionPerformed
      if (s28 >= 2) {seat28.setBackground(Color.GREEN);
a28=1;
s28=0;
      }
else {
seat28.setBackground(Color.gray);
a28=0;
s28=2;
}     // TODO add your handling code here:
    }//GEN-LAST:event_seat30ActionPerformed

    private void seat29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat29ActionPerformed
      if(s29>=2 ){seat29.setBackground(Color.GREEN);
a29=1;
s29=0;
}
else{
seat29.setBackground(Color.gray);
a29=0;
s29=2;
}    // TODO add your handling code here:
    }//GEN-LAST:event_seat29ActionPerformed

    private void seat23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat23ActionPerformed
      if (s23>=2){ seat23.setBackground(Color.GREEN);
a23=1;
s23=0;
}
else {
seat23.setBackground(Color.gray);
a23=0;
s23=2;
}   // TODO add your handling code here:
    }//GEN-LAST:event_seat23ActionPerformed

    private void seat17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat17ActionPerformed
       if (s17 >=2 ) {seat17.setBackground(Color.GREEN);
a17=1;
s17= 0;
}
else {
seat17.setBackground(Color.gray);
a17=0;
s17=2;
}   // TODO add your handling code here:
    }//GEN-LAST:event_seat17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_seat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton ok;
    private javax.swing.JButton seat1;
    private javax.swing.JButton seat10;
    private javax.swing.JButton seat11;
    private javax.swing.JButton seat12;
    private javax.swing.JButton seat13;
    private javax.swing.JButton seat14;
    private javax.swing.JButton seat15;
    private javax.swing.JButton seat16;
    private javax.swing.JButton seat17;
    private javax.swing.JButton seat18;
    private javax.swing.JButton seat19;
    private javax.swing.JButton seat2;
    private javax.swing.JButton seat20;
    private javax.swing.JButton seat21;
    private javax.swing.JButton seat22;
    private javax.swing.JButton seat23;
    private javax.swing.JButton seat24;
    private javax.swing.JButton seat25;
    private javax.swing.JButton seat26;
    private javax.swing.JButton seat27;
    private javax.swing.JButton seat28;
    private javax.swing.JButton seat29;
    private javax.swing.JButton seat3;
    private javax.swing.JButton seat30;
    private javax.swing.JButton seat31;
    private javax.swing.JButton seat32;
    private javax.swing.JButton seat4;
    private javax.swing.JButton seat5;
    private javax.swing.JButton seat6;
    private javax.swing.JButton seat7;
    private javax.swing.JButton seat8;
    private javax.swing.JButton seat9;
    // End of variables declaration//GEN-END:variables
}
